# Generated by Django 3.2.9 on 2022-06-04 14:47

import app_notifications.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255, null=True, verbose_name='Notification Type')),
                ('payload', models.JSONField(default=app_notifications.models.notification_payload_default, verbose_name='Notification Payload')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Notification Text')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Notification',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='seened at')),
                ('notification', models.ForeignKey(db_column='notification_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipients', to='app_notifications.notification', verbose_name='notification')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Notification Recipient',
                'db_table': 'notification_recipient',
                'ordering': ['-id'],
            },
        ),
    ]
